### ISSUE TITLE
增加手动编辑SSL域名列表

### ISSUE THREAD

**Issue by londry** [londry/Encryption365_Baota#1]
### 描述
- 部分高级用户可能需要在申请证书时，自由选择所需申请SSL的域名(增加或移除)
- 站点的某些已经检测的合法域名可能并不需要证书，届时可以考虑需要手动移除或勾选进行SSL申请

考虑增加高级模式或开放域名编辑框

**Comment by jiqing112** [comment]
还有个问题，插件会因为莫名原因申请证书失败，订单状态会一直卡在  验证中 ，只要删除网站重新在插件里申请会申请成功。

不是所有网站都能删除重建的，建议在插件里加一个重新申请的功能

**Comment by londry** [comment]
> 还有个问题，插件会因为莫名原因申请证书失败，订单状态会一直卡在 验证中 ，只要删除网站重新在插件里申请会申请成功。
> 
> 不是所有网站都能删除重建的，建议在插件里加一个重新申请的功能

我们已经在 https://github.com/londry/Encryption365_Baota/commit/9fa4e7dd341d18d7d12008932e2dd9c1496f231d 提交中增加了 “删除证书订单” 按钮，您可以移除未成功的订单，然后重新修改域名申请。当然，我们还增加了许多其他的操作来帮助您更加顺利的申请SSL证书。

```
增加手动编辑SSL域名列表
```
这个需求已经被移除，因为暂时不符合我们的预期。
