### ISSUE TITLE
在aapanel里导入插件用不了？

### ISSUE THREAD

**Issue by louiejordan** [londry/Encryption365_Baota#14]
按说宝塔能用aapanel也能用，但是aapanel我导入插件后，证书一直在签发中

**Comment by londry** [comment]
您好，理论上是支持的，一直签发中此问题可能是由于Cron没执行导致的，建议您添加我们的售后微信群获取帮助

**Comment by londry** [comment]
> 按说宝塔能用aapanel也能用，但是aapanel我导入插件后，证书一直在签发中

Cron没有运行起来，建议检查Cron日志，或重新 编辑 保存 一下 Cron任务，即可。

其他问题，您可以反馈您的Cron日志到此，以便于我们排查。

祝好！
