### ISSUE TITLE
老是不能自动续签，太耽误事了

### ISSUE THREAD

**Issue by dylanbai8** [londry/Encryption365_Baota#16]
最新 1.3.1版 宝塔插件 GitHub版
文件验证成功，就是不发证书。。。
希望尽快改进啊，
耽误事，只能临时弃用了

**Comment by londry** [comment]
Cron没有运行起来，建议检查Cron日志，或重新 编辑 保存 一下 Cron任务，即可。

其他问题，您可以反馈您的Cron日志到此，以便于我们排查。

祝好！

**Comment by londry** [comment]
> 最新 1.3.1版 宝塔插件 GitHub版
> 文件验证成功，就是不发证书。。。
> 希望尽快改进啊，
> 耽误事，只能临时弃用了

Cron没有运行起来，建议检查Cron日志，或重新 编辑 保存 一下 Cron任务，即可。

其他问题，您可以反馈您的Cron日志到此，以便于我们排查。

祝好！
