### ISSUE TITLE
Ubuntu 系统可能会出现定时任务不执行

### ISSUE THREAD

**Issue by londry** [londry/Encryption365_Baota#2]
Ubuntu 系统可能会出现定时任务的兼容性问题，临床表现可能如下：

- 证书自动化更新状态不执行
- 自动安装失败
- 自动续费失败

考虑是Python ENV问题？

**Comment by jiqing112** [comment]
Centos 8 有类似的问题，手动跟进

**Comment by londry** [comment]
> Centos 8 有类似的问题，手动跟进

OK

**Comment by londry** [comment]
> Centos 8 有类似的问题，手动跟进
我们已经在新的CentOS8中测试，运行和申请正常
并且已经修复了Ubuntu定时任务兼容问题 https://github.com/londry/Encryption365_Baota/commit/4a42149bcc5e4ddc60e04a7f01eda7d6888cd9b7

如有新的测试问题，请随时反馈。
