### ISSUE TITLE
有没有办法 API 改验证方式为 DNS？

### ISSUE THREAD

**Issue by djunny** [londry/Encryption365_Baota#3]
分布式下 http 验证不方便

看了一圈 API 里也没有对应参数

有 API 接口说明文档更好

**Comment by londry** [comment]
您好，我们会在近期安排时间整理Encryption365™ API

**Comment by londry** [comment]
> 分布式下 http 验证不方便
> 
> 看了一圈 API 里也没有对应参数
> 
> 有 API 接口说明文档更好

我们已经整理了部分Encryption365 API接口文档，包含您提到的 DCV Change API，敬请参考： https://chat.trustocean.com/topic/index?id=4

**Comment by djunny** [comment]
domain 无论是传数组, 单个, 还是逗号分隔的，都提示：

Array
(
    [result] => error
    [message] => DCV操作中未找到对应的域名!
)

**Comment by londry** [comment]
> domain 无论是传数组, 单个, 还是逗号分隔的，都提示：
> 
> Array
> (
> [result] => error
> [message] => DCV操作中未找到对应的域名!
> )

提供订单号码，我帮助您查一下日志，看看问题在哪里。

**Comment by djunny** [comment]
154077

**Comment by londry** [comment]
> 154077

立即为您核实情况，稍等

**Comment by londry** [comment]
> 154077

请现在尝试一下。

**Comment by djunny** [comment]
请问是一张证书有多少个域名，就要请求多少次这个接口？

参数是传数组还是逗号分隔符还是？

还是说一次可以把所有域名提交过来？

另外建议 /cert/create 接口直接加一个 method 参数可以减少请求

**Comment by londry** [comment]
> 请问是一张证书有多少个域名，就要请求多少次这个接口？
> 
> 参数是传数组还是逗号分隔符还是？
> 
> 还是说一次可以把所有域名提交过来？
> 
> 另外建议 /cert/create 接口直接加一个 method 参数可以减少请求

此接口每次只能为1个域名修改dcv方式，多个域名需要分别调用。

【以标记处理】/cert/create 接口增加 method 参数

**Comment by londry** [comment]
> 请问是一张证书有多少个域名，就要请求多少次这个接口？
> 
> 参数是传数组还是逗号分隔符还是？
> 
> 还是说一次可以把所有域名提交过来？
> 
> 另外建议 /cert/create 接口直接加一个 method 参数可以减少请求

请您测试：在调用 /cert/create 接口时尝试添加额外参数: 
| 参数名称 | 类型 |最大长度(字符)|必须传入? | 说明|
| - | - | - | - | - |
| dcv_method | string |13| 否 | 用于指定域名的DCV验证方式，如果不传入，则默认全部域名都采用 `HTTP` 方式验证，如果传入，则采用传入的方式覆盖默认验证方式。该参数的可选值请参看下列`dcv_method`参数说明 |

## dcv_method 参数说明
下面这些值是可用于在访问 `/cert/create` 接口时传入到 `dcv_method` 变量的魔术值：
| 可选值 | 作用说明 |
| - | - |
| ALLDNSCNAME | 设置全部域名(IP地址除外)的验证方式为 DNS CNAME 验证。 |
| ALLHTTP | 设置全部域名(包含IP地址)的验证方式为 HTTP-80 文件验证。 |
| ALLHTTPS | 设置全部域名(包含IP地址)的验证方式为 HTTPS-443 验证。 |
| ALLADMINEMAIL | 设置全部域名(IP地址除外)的验证方式为 admin@ 域名邮箱接收邮件手动完成验证。 |

**Comment by djunny** [comment]
赞一个，速度 👍🏻

**Comment by londry** [comment]
> 赞一个，速度 👍🏻

感谢！期待您的测试反馈。

**Comment by djunny** [comment]
```html

<html>   <head>       <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>       <title>Slim Application Error</title>       <style>           body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif}           h1{margin:0;font-size:48px;font-weight:normal;line-height:48px}           strong{display:inline-block;width:65px}       </style>   </head>   <body>       <h1>Slim Application Error</h1>       <div><p>The application could not run because of the following error:</p><h2>Details</h2><div><strong>Type:</strong> Error</div><div><strong>Code:</strong> 0</div><div><strong>Message:</strong> [] operator not supported for strings</div><div><strong>File:</strong> /home/wwwroot/console.trustocean.com/encryption365/application/Model/SSLOrder.php</div><div><strong>Line:</strong> 217</div><h2>Trace</h2><pre>#0 /home/wwwroot/console.trustocean.com/encryption365/application/Controller/CertController.php(61): Encryption365\Server\Model\SSLOrder-&gt;setDcvMethod('ALLDNSCNAME')
#1 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Encryption365\Server\Controller\CertController-&gt;create(Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array)
#2 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/Routing/Route.php(381): Slim\Handlers\Strategies\RequestResponse-&gt;__invoke(Array, Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array)
#3 /home/wwwroot/console.trustocean.com/encryption365/application/Middleware/Authorization.php(66): Slim\Routing\Route-&gt;handle(Object(Slim\Psr7\Request))
#4 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/MiddlewareDispatcher.php(188): Encryption365\Server\Middleware\Authorization-&gt;__invoke(Object(Slim\Psr7\Request), Object(Slim\Routing\Route))
#5 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous-&gt;handle(Object(Slim\Psr7\Request))
#6 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher-&gt;handle(Object(Slim\Psr7\Request))
#7 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher-&gt;handle(Object(Slim\Psr7\Request))
#8 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route-&gt;run(Object(Slim\Psr7\Request))
#9 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Slim\Routing\RouteRunner-&gt;handle(Object(Slim\Psr7\Request))
#10 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware-&gt;process(Object(Slim\Psr7\Request), Object(Slim\Routing\RouteRunner))
#11 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous-&gt;handle(Object(Slim\Psr7\Request))
#12 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher-&gt;handle(Object(Slim\Psr7\Request))
#13 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/App.php(199): Slim\App-&gt;handle(Object(Slim\Psr7\Request))
#14 /home/wwwroot/console.trustocean.com/encryption365/public/index.php(70): Slim\App-&gt;run()
#15 {main}</pre></div>       <a href="#" onClick="window.history.go(-1)">Go Back</a>   </body></html>

```

现在新申请报错了。

**Comment by londry** [comment]
> ```
> <html>   <head>       <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>       <title>Slim Application Error</title>       <style>           body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif}           h1{margin:0;font-size:48px;font-weight:normal;line-height:48px}           strong{display:inline-block;width:65px}       </style>   </head>   <body>       <h1>Slim Application Error</h1>       <div><p>The application could not run because of the following error:</p><h2>Details</h2><div><strong>Type:</strong> Error</div><div><strong>Code:</strong> 0</div><div><strong>Message:</strong> [] operator not supported for strings</div><div><strong>File:</strong> /home/wwwroot/console.trustocean.com/encryption365/application/Model/SSLOrder.php</div><div><strong>Line:</strong> 217</div><h2>Trace</h2><pre>#0 /home/wwwroot/console.trustocean.com/encryption365/application/Controller/CertController.php(61): Encryption365\Server\Model\SSLOrder-&gt;setDcvMethod('ALLDNSCNAME')
> #1 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Encryption365\Server\Controller\CertController-&gt;create(Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array)
> #2 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/Routing/Route.php(381): Slim\Handlers\Strategies\RequestResponse-&gt;__invoke(Array, Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array)
> #3 /home/wwwroot/console.trustocean.com/encryption365/application/Middleware/Authorization.php(66): Slim\Routing\Route-&gt;handle(Object(Slim\Psr7\Request))
> #4 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/MiddlewareDispatcher.php(188): Encryption365\Server\Middleware\Authorization-&gt;__invoke(Object(Slim\Psr7\Request), Object(Slim\Routing\Route))
> #5 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous-&gt;handle(Object(Slim\Psr7\Request))
> #6 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher-&gt;handle(Object(Slim\Psr7\Request))
> #7 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher-&gt;handle(Object(Slim\Psr7\Request))
> #8 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route-&gt;run(Object(Slim\Psr7\Request))
> #9 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Slim\Routing\RouteRunner-&gt;handle(Object(Slim\Psr7\Request))
> #10 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware-&gt;process(Object(Slim\Psr7\Request), Object(Slim\Routing\RouteRunner))
> #11 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous-&gt;handle(Object(Slim\Psr7\Request))
> #12 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher-&gt;handle(Object(Slim\Psr7\Request))
> #13 /home/wwwroot/console.trustocean.com/encryption365/vendor/slim/slim/Slim/App.php(199): Slim\App-&gt;handle(Object(Slim\Psr7\Request))
> #14 /home/wwwroot/console.trustocean.com/encryption365/public/index.php(70): Slim\App-&gt;run()
> #15 {main}</pre></div>       <a href="#" onClick="window.history.go(-1)">Go Back</a>   </body></html>
> ```
> 
> 现在新申请报错了。

忘记上传 😂，，，请再次尝试。

**Comment by djunny** [comment]
OK~完美通过测试~ 后续把 PHP 的库开源分享出来。

顺带问下，一个账号申请频率和证书上限有没有限制，

lets 上是有相应的频率和限制的，这边如果有限制的话是什么样的？

**Comment by londry** [comment]
> OK，完美通过测试 ~ 后续我把 PHP 的库开源分享出来。
> 
> 顺带问下，一个账号申请频率和证书上限有没有限制，
> 
> lets 上是有相应的频率和限制的，这边如果有限制的话是什么样的？

目前没有得到任何的频率限制。我们 Encryption365 板块在很大程度上是作为国内 Lets 的替代方案储备，因此请放心使用。

**Comment by londry** [comment]
您好，我现在需要关闭这个线程了，如果此后存在其他问题，建议您新开一个issue或者发布至 chat.trustocean.com 以便于我们跟踪。

祝好！
