### ISSUE TITLE
ssl OCSP Stapling 慢

### ISSUE THREAD

**Issue by djunny** [londry/Encryption365_Baota#4]
发现 OCSP Stapling 服务器不通，似乎也验证不了

导致浏览器加载站点过慢...不知道其它有没有人遇到...

**Comment by londry** [comment]
目前 SECTIGO CA已经着手切换OCSP CDN服务提供商。
额外的，如果您的服务器位于中国境内，建议您在OCSP Stapling中配合使用我们设置的OCSP服务器镜像地址：http://ocsp.trustocean.com
