### ISSUE TITLE
PHP-7.3啥时候能支持

### ISSUE THREAD

**Issue by baiyanghk** [londry/Encryption365_Baota#5]
看介绍应该是不支持大于7.1的PHP版本，啥时候能升级下高版本的兼容性

**Comment by londry** [comment]
> 看介绍应该是不支持大于7.1的PHP版本，啥时候能升级下高版本的兼容性

>=7.1 都可以支持呢，大于等于7.1版本的PHP环境都可以支持的。PHP7.2 PHP7.3 PHP7.4 或者以上版本都支持的。有问题也可以在交流群里沟通！
