### ISSUE TITLE
PHP8.0 作为宝塔初始版本时可能存在兼容问题

### ISSUE THREAD

**Issue by londry** [londry/Encryption365_Baota#6]
系统：Debian GNU/Linux 10(Py3.7.8)
PHP版本：8.0
问题描述：安装插件后->启动->创建数据库表失败，导致服务不正常、不工作

需要测试PHP8版本兼容问题、完成后测试多个系统中PHP8。

**Comment by ayaka209** [comment]
不仅初始，在7.4正常使用本插件后，安装php8也会有问题，除了error_reporting外还提示curl错误，curl扩展已开

**Comment by londry** [comment]
> 不仅初始，在7.4正常使用本插件后，安装php8也会有问题，除了error_reporting外还提示curl错误，curl扩展已开
> 切换php命令行版本到7.4后，仍然不行，最终只能删除php8后方正常
> ubuntu 20.04

此问题已在  https://github.com/londry/Encryption365_Baota/commit/280e6b3562fef0664699ca028a2a45c5ce214874  中被标记为解决，我们将会在v1.3版本中测试发布
