### ISSUE TITLE
请问，我网站搬家了，重新安装了插件，又提交了ssl申请，现在一直是验证中？

### ISSUE THREAD

**Issue by uubxs** [londry/Encryption365_Baota#7]
不知道这样的操作对吗？
期待您的回复，感谢！

**Comment by londry** [comment]
您好，建议您执行如下操作
1、检查下宝塔面板菜单->定时任务->Encryption365 SSL自动任务->右侧日志，查看是否有报错信息，有？请回复到这里排查。
2、确保您的站点迁移后域名解析正常、且网站可以正常访问么？正常的话应该为其他问题。
3、提供已经下单的订单号码，可以在站点证书页面查看到，我帮您检查是否签发。

期待您的答复。或者点击最新版本的插件左侧菜单联系客服，联系我们在线客服发送具体截图获取帮助。

**Comment by londry** [comment]
> 不知道这样的操作对吗？
> 期待您的回复，感谢！


您好，建议您执行如下操作
1、检查下宝塔面板菜单->定时任务->Encryption365 SSL自动任务->右侧日志，查看是否有报错信息，有？请回复到这里排查。
2、确保您的站点迁移后域名解析正常、且网站可以正常访问么？正常的话应该为其他问题。
3、提供已经下单的订单号码，可以在站点证书页面查看到，我帮您检查是否签发。

期待您的答复。或者点击最新版本的插件左侧菜单联系客服，联系我们在线客服发送具体截图获取帮助。

**Comment by uubxs** [comment]
订单编号 | 166066
网站运行正常，计划任务 日志显示都是成功的。
因为是搬家，所以之前签发的还在，但是怕不能续签，所以我搬家后又申请了。帮忙看下哈，感谢您的回复。

**Comment by londry** [comment]
请你检查一下网站或CDN配置，系统在访问验证文件时出现报错：

确保可以正常验证连接：
http://你的顶级域名.com/.well-know/pki-validation/54938C8862E36A090605DB3C9CFD1BB9.txt

当前报错截图
![72B3953A-BE35-417E-BB72-900D80155BC6](https://user-images.githubusercontent.com/2663428/103440041-5ffd7080-4c7d-11eb-98f9-4dc5333d1882.jpeg)

正常访问后请告诉我们

**Comment by uubxs** [comment]
嗯嗯，我刚才动了什么东西，现在访问确实有问题了，我去检查下。

**Comment by uubxs** [comment]
哥，我现在是重新安装了网站。网站正常咯。
但这个链接没法验证哦，：
http://你的顶级域名.com/.well-know/pki-validation/54938C8862E36A090605DB3C9CFD1BB9.txt

还有您能否帮我删除上图？暴露域名了

**Comment by londry** [comment]
已经删除


您在public目录下新建一下文件夹路径

/.well-know/pki-validation/

然后在里面创建一个文本文件

54938C8862E36A090605DB3C9CFD1BB9.txt

文件内容一共三行，只能三行：
11b491b7971249f2f2fc870d46f12dfe96474b9c720dce7c080778911ef849cd
comodoca.com
cab202129675


然后再次访问试一下。

**Comment by uubxs** [comment]
添加后是可以访问这个的

**Comment by uubxs** [comment]
文件验证好像不行，我刚是了DNS验证，很快通过了。感谢有些您！

**Comment by londry** [comment]
👌，我们将考虑在下个版本中展示包括DNS验证信息
